# PATH name
set(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/output) # ROOT
# set(OUTPUT_EXECUTE_DIRECTORY )
set(INSTALL_LIBRARY_DIRECTORY ${CMAKE_INSTALL_PREFIX}/lib) # Library path
set(INSTALL_INCLUDE_DIRECTORY ${CMAKE_INSTALL_PREFIX}/include) # Header path